#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/_common.sh"
read_hook_input

file="$(tool_file_path)"
if [[ -z "$file" ]]; then
  allow_tool
fi

basename_file="$(basename "$file")"

hard_blocked=(
  '.env'
  '.env.production'
  '.env.staging'
  '.env.local'
  'routeTree.gen.ts'
)

for name in "${hard_blocked[@]}"; do
  if [[ "$basename_file" == "$name" ]] || [[ "$file" == *"/$name" ]]; then
    deny_tool \
      "Protected file cannot be edited by the agent: $file" \
      "Do not edit $file. Use .env.example for documented placeholders; routeTree.gen.ts is generated by TanStack Router."
  fi
done

if echo "$file" | grep -qE '\.(pem|key)$'; then
  deny_tool "Protected credential file: $file"
fi

if echo "$file" | grep -qE '/\.git/'; then
  deny_tool "Git metadata is not editable: $file"
fi

if echo "$file" | grep -qE '/secrets/'; then
  deny_tool "Secrets directory is protected: $file"
fi

warn_only=(
  'tsconfig.json'
  'wrangler.jsonc'
  'vite.config.ts'
  'package.json'
  'bun.lock'
)

for name in "${warn_only[@]}"; do
  if [[ "$basename_file" == "$name" ]]; then
    echo "CAUTION: guarded config file $file — confirm change is intentional." >&2
  fi
done

allow_tool
