#!/usr/bin/env bash
# scripts/load-secrets.sh
# Pulls credentials from 1Password and writes a local .env file.
# Requires: op CLI installed and authenticated (https://developer.1password.com/docs/cli)
# Usage: bash scripts/load-secrets.sh
#
# 1Password item: "JRE Notion Workers - API Credentials"
# Vault: set OP_VAULT env var or edit VAULT below (default: Dev).
#
# This script is open-source safe — it contains no real secrets.
# Contributors who don't use 1Password should populate .env manually
# using .env.example as a reference.

set -euo pipefail

ITEM="JRE Notion Workers - API Credentials"
VAULT="${OP_VAULT:-Dev}"

echo "Fetching secrets from 1Password (vault:$VAULT, item:$ITEM)..."

cat > .env <<EOF
# Auto-generated by scripts/load-secrets.sh — do not commit
NOTION_TOKEN=$(op item get "$ITEM" --vault "$VAULT" --fields label=NOTION_TOKEN)
DOCS_DATABASE_ID=$(op item get "$ITEM" --vault "$VAULT" --fields label=DOCS_DATABASE_ID)
HOME_DOCS_DATABASE_ID=$(op item get "$ITEM" --vault "$VAULT" --fields label=HOME_DOCS_DATABASE_ID)
TASKS_DATABASE_ID=$(op item get "$ITEM" --vault "$VAULT" --fields label=TASKS_DATABASE_ID)
EOF

echo ".env written. Run 'bun run dev' to start local development."
