#!/usr/bin/env bash
# scripts/load-secrets.sh
# Pulls credentials from 1Password and writes a local .env file for development.
# Requires: op CLI installed and authenticated (https://developer.1password.com/docs/cli)
# Usage: bash scripts/load-secrets.sh
#
# 1Password item: "JRE Notion Workers - API Credentials"
# Vault: set OP_VAULT env var or edit VAULT below (default: Dev).
#
# For deployed workers, use scripts/sync-notion-worker-secrets.sh instead.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

ITEM="JRE Notion Workers - API Credentials"
VAULT="${OP_VAULT:-Dev}"

get_field() {
  local label="$1"
  op item get "$ITEM" --vault "$VAULT" --fields "label=$label" 2>/dev/null || true
}

echo "Fetching secrets from 1Password (vault:$VAULT, item:$ITEM)..."

NTN_TOKEN="$(get_field NTN_API_TOKEN)"
if [[ -z "$NTN_TOKEN" ]]; then
  NTN_TOKEN="$(get_field NOTION_TOKEN)"
fi

cat > .env <<EOF
# Auto-generated by scripts/load-secrets.sh — do not commit
NTN_API_TOKEN=${NTN_TOKEN}
DOCS_DATABASE_ID=$(get_field DOCS_DATABASE_ID)
HOME_DOCS_DATABASE_ID=$(get_field HOME_DOCS_DATABASE_ID)
TASKS_DATABASE_ID=$(get_field TASKS_DATABASE_ID)
DEAD_LETTERS_DATABASE_ID=$(get_field DEAD_LETTERS_DATABASE_ID)
SYSTEM_CONTROL_PLANE_PAGE_ID=$(get_field SYSTEM_CONTROL_PLANE_PAGE_ID)
GITHUB_ITEMS_DATABASE_ID=$(get_field GITHUB_ITEMS_DATABASE_ID)
GITHUB_TOKEN=$(get_field GITHUB_TOKEN)
FOLLOW_UP_TRACKER_DATABASE_ID=$(get_field FOLLOW_UP_TRACKER_DATABASE_ID)
AI_MEETINGS_DATABASE_ID=$(get_field AI_MEETINGS_DATABASE_ID)
CLIENTS_DATABASE_ID=$(get_field CLIENTS_DATABASE_ID)
CONTACTS_DATABASE_ID=$(get_field CONTACTS_DATABASE_ID)
PROJECTS_DATABASE_ID=$(get_field PROJECTS_DATABASE_ID)
DECISION_LOG_DATABASE_ID=$(get_field DECISION_LOG_DATABASE_ID)
LABEL_REGISTRY_DATABASE_ID=$(get_field LABEL_REGISTRY_DATABASE_ID)
TIME_LOG_DATABASE_ID=$(get_field TIME_LOG_DATABASE_ID)
AGENT_OPS_DATABASE_ID=$(get_field AGENT_OPS_DATABASE_ID)
CLIENT_SHARED_DOCUMENTS_DATABASE_ID=$(get_field CLIENT_SHARED_DOCUMENTS_DATABASE_ID)
EOF

echo ".env written. Run 'bun run dev' or 'bun test' with --env-file=.env"
echo "To sync deployed worker secrets: bash scripts/sync-notion-worker-secrets.sh"
